DROP DATABASE IF EXISTS TEST;
CREATE DATABASE TEST;
USE TEST;

DROP PROCEDURE IF EXISTS CONDICIONAL_1()
DELIMITER $$
CREATE PROCEDURE CONDICIONAL_1(IN EDAD INT)
BEGIN
    IF EDAD < 18 THEN
		SELECT "Eren menor de edad";
	ELSE
		SELECT "Eres mayor de edad";
	END IF;
END $$
DELIMITER ;

CALL CONDICIONAL_1(17);

DROP PROCEDURE IF EXISTS CONDICIONAL_2()
DELIMITER $$
CREATE PROCEDURE CONDICIONAL_2(in color VARCHAR(10))
BEGIN
    CASE color
		WHEN "rojo" THEN
			SELECT "No puedes pasar";
		WHEN "rojo" THEN
			SELECT "Pasa con precaucion";
		WHEN "rojo" THEN
			SELECT "Puedes pasar";
		else
			SELECT "No conozco";
	END CASE;
END $$
DELIMITER ;

CALL CONDICIONAL_2("rojo");

DROP PROCEDURE IF EXISTS CONDICIONAL_3()
DELIMITER $$
CREATE PROCEDURE CONDICIONAL_3(IN n1 INT, IN n2 INT)
BEGIN
    IF n1 < n2 THEN
		SELECT "n2 es mayor que n1";
	ELSEIF n1 > n2 THEN
		SELECT "n1 es mayor que n2";
	ELSE
		SELECT "n2 y n1 son iguales"
	END IF;
END $$
DELIMITER ;

CALL CONDICIONAL_3(20, 32);

CREATE TABLE NUM(
	NUM INT(12),
    DAT VARCHAR(20)
)ENGINE=InnoDB;

DROP PROCEDURE IF EXISTS BUCLES_1()
DELIMITER $$
CREATE PROCEDURE  BUCLES_1(IN n1 INT)
BEGIN
	DECLARE i INT DEFAULT 1;
	WHILE i <= n1 DO
		IF mod(i,2) THEN
			INSERT INTO NUM VALUES(i, "es impar");
		ELSE
			INSERT INTO NUM VALUES(i, "es par");
		END IF;
		SET i = i + 1;
	END WHILE;
    SELECT * FROM NUM;
END $$
DELIMITER ;

CALL  BUCLES_1(20);