USE JARDINERIA;

CREATE OR REPLACE VIEW listado_pedidos_clientes AS
SELECT CONCAT(C.NOMBRE_CONTACTO, " ", C.APELLIDO_CONTACTO) AS NOMBRE, TELEFONO, CIUDAD, PAIS,
       P.CODIGO_PEDIDO, P.FECHA_PEDIDO, P.FECHA_ESPERADA, P.FECHA_ENTREGA, SUM(DP.PRECIO_UNIDAD * DP.CANTIDAD) AS TOTAL
FROM CLIENTE C INNER JOIN PEDIDO P ON C.CODIGO_CLIENTE = P.CODIGO_CLIENTE
INNER JOIN DETALLE_PEDIDO DP ON P.CODIGO_PEDIDO = DP.CODIGO_PEDIDO
GROUP BY P.CODIGO_PEDIDO;

SELECT NOMBRE, CODIGO_PEDIDO FROM listado_pedidos_clientes
WHERE FECHA_ENTREGA IS NULL;

SELECT NOMBRE, COUNT(NOMBRE) FROM listado_pedidos_clientes
GROUP BY NOMBRE;

SELECT NOMBRE, MAX(TOTAL), MIN(TOTAL) FROM listado_pedidos_clientes
GROUP BY NOMBRE;

USE EMPRESA;
CREATE OR REPLACE VIEW ALL_WORKER AS
SELECT E.NOMBRE AS EMP, SURNAME, LASTNAME, 
       D.NOMBRE AS DEP, PRESUPUESTO 
FROM EMPLEADO E LEFT JOIN DEPARTAMENTO D 
ON E.DEPARTAMENTO = D.CODIGO;

CREATE OR REPLACE VIEW ALL_WORKER_DEP AS
SELECT D.NOMBRE AS DEP, COUNT(E.DEPARTAMENTO)
FROM EMPLEADO E RIGHT JOIN DEPARTAMENTO D 
ON E.DEPARTAMENTO = D.CODIGO
GROUP BY D.NOMBRE;